language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - XDEBUG_MODE=coverage

sudo: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
